// ClientUI.js
(function(){
Type.registerNamespace('ClientUI.Model');ClientUI.Model.Contact=function(){ClientUI.Model.Contact.initializeBase(this,['contact']);}
ClientUI.Model.Contact.prototype={contactid:null,firstname:null,lastname:null,preferredcontactmethodcode:null,parentcustomerid:null}
Type.registerNamespace('ClientUI.ViewModel');ClientUI.ViewModel.ContactsViewModel=function(){this.ErrorMessage=ko.observable();this.AllowAddNew=ko.observable(true);this.Contacts=new SparkleXrm.GridEditor.EntityDataViewModel(10,ClientUI.Model.Contact,true);ClientUI.ViewModel.ContactsViewModel.initializeBase(this);this.ContactEdit=ko.observable(new ClientUI.ViewModel.ObservableContact());this.ContactEdit().add_onSaveComplete(ss.Delegate.create(this,this.$1_0));}
ClientUI.ViewModel.ContactsViewModel.prototype={ContactEdit:null,$1_0:function($p0){if($p0==null){this.ErrorMessage(null);}else{this.ErrorMessage($p0);}},search:function(){this.Contacts.set_fetchXml("<fetch version='1.0' output-format='xml-platform' mapping='logical' returntotalrecordcount='true' no-lock='true' distinct='false' count='{0}' paging-cookie='{1}' page='{2}'>\r\n  <entity name='contact'>\r\n    <attribute name='firstname' />\r\n    <attribute name='lastname' />\r\n    <attribute name='contactid' />\n    {3}\r\n  </entity>\r\n</fetch>");this.Contacts.refresh();},AddNewCommand:function(){},DeleteSelectedCommand:function(){},OpenAssociatedSubGridCommand:function(){}}
ClientUI.ViewModel.ObservableContact=function(){this.contactid=ko.observable();this.firstname=ko.observable();this.lastname=ko.observable();this.preferredcontactmethodcode=ko.observable();this.parentcustomerid=ko.observable();ClientUI.ViewModel.ObservableContact.initializeBase(this);}
ClientUI.ViewModel.ObservableContact.prototype={add_onSaveComplete:function(value){this.$1_0=ss.Delegate.combine(this.$1_0,value);},remove_onSaveComplete:function(value){this.$1_0=ss.Delegate.remove(this.$1_0,value);},$1_0:null,$1_1:function(){var $0=new ClientUI.Model.Contact();$0.contactid=this.contactid();$0.firstname=this.firstname();$0.lastname=this.lastname();$0.parentcustomerid=this.parentcustomerid();$0.preferredcontactmethodcode=this.preferredcontactmethodcode();return $0;},saveCommand:function(){this.isBusy(true);var $0=this.$1_1();Xrm.Sdk.OrganizationServiceProxy.beginCreate($0,ss.Delegate.create(this,function($p1_0){
try{this.contactid(Xrm.Sdk.OrganizationServiceProxy.endCreate($p1_0));this.$1_0(null);}catch($1_0){this.$1_0($1_0.message);}finally{this.isBusy(false);}}));}}
Type.registerNamespace('ClientUI.View');ClientUI.View.ContactsView=function(){}
ClientUI.View.ContactsView.Init=function(){Xrm.PageEx.majorVersion=2013;ClientUI.View.ContactsView.vm=new ClientUI.ViewModel.ContactsViewModel();var $0=new SparkleXrm.GridEditor.GridDataViewBinder();var $1=SparkleXrm.GridEditor.GridDataViewBinder.parseLayout('First Name,firstname,250,Last Name,lastname,250');var $2=$0.dataBindXrmGrid(ClientUI.View.ContactsView.vm.Contacts,$1,'container','pager',true,false);SparkleXrm.ViewBase.registerViewModel(ClientUI.View.ContactsView.vm);$(function(){
ClientUI.View.ContactsView.vm.search();});}
ClientUI.Model.Contact.registerClass('ClientUI.Model.Contact',Xrm.Sdk.Entity);ClientUI.ViewModel.ContactsViewModel.registerClass('ClientUI.ViewModel.ContactsViewModel',SparkleXrm.ViewModelBase);ClientUI.ViewModel.ObservableContact.registerClass('ClientUI.ViewModel.ObservableContact',SparkleXrm.ViewModelBase);ClientUI.View.ContactsView.registerClass('ClientUI.View.ContactsView');ClientUI.View.ContactsView.vm=null;})();// This script was generated using Script# v0.7.4.0
