// ClientUI.js
(function(){
Type.registerNamespace('ClientUI.Model');ClientUI.Model.Contact=function(){ClientUI.Model.Contact.initializeBase(this,['contact']);}
ClientUI.Model.Contact.prototype={contactid:null,firstname:null,lastname:null,preferredcontactmethodcode:null,parentcustomerid:null}
Type.registerNamespace('ClientUI.ViewModel');ClientUI.ViewModel.HelloWorldViewModel=function(){ClientUI.ViewModel.HelloWorldViewModel.initializeBase(this);this.Message=ko.observable('Hello World');}
ClientUI.ViewModel.HelloWorldViewModel.prototype={Message:null,FooCommand:function(){this.Message(String.format('The time now is {0}',Date.get_now().toLocaleTimeString()));}}
ClientUI.ViewModel.ObservableContact=function(){this.contactid=ko.observable();this.firstname=ko.observable();this.lastname=ko.observable();this.preferredcontactmethodcode=ko.observable();this.parentcustomerid=ko.observable();ClientUI.ViewModel.ObservableContact.initializeBase(this);}
ClientUI.ViewModel.ObservableContact.prototype={add_onSaveComplete:function(value){this.$1_0=ss.Delegate.combine(this.$1_0,value);},remove_onSaveComplete:function(value){this.$1_0=ss.Delegate.remove(this.$1_0,value);},$1_0:null,$1_1:function(){var $0=new ClientUI.Model.Contact();$0.contactid=this.contactid();$0.firstname=this.firstname();$0.lastname=this.lastname();$0.parentcustomerid=this.parentcustomerid();$0.preferredcontactmethodcode=this.preferredcontactmethodcode();return $0;},saveCommand:function(){this.isBusy(true);var $0=this.$1_1();Xrm.Sdk.OrganizationServiceProxy.beginCreate($0,ss.Delegate.create(this,function($p1_0){
try{this.contactid(Xrm.Sdk.OrganizationServiceProxy.endCreate($p1_0));this.$1_0(null);}catch($1_0){this.$1_0($1_0.message);}finally{this.isBusy(false);}}));}}
Type.registerNamespace('ClientUI.View');ClientUI.View.HelloWorldView=function(){}
ClientUI.View.HelloWorldView.Init=function(){Xrm.PageEx.majorVersion=2013;ClientUI.View.HelloWorldView.vm=new ClientUI.ViewModel.HelloWorldViewModel();SparkleXrm.ViewBase.registerViewModel(ClientUI.View.HelloWorldView.vm);}
ClientUI.Model.Contact.registerClass('ClientUI.Model.Contact',Xrm.Sdk.Entity);ClientUI.ViewModel.HelloWorldViewModel.registerClass('ClientUI.ViewModel.HelloWorldViewModel',SparkleXrm.ViewModelBase);ClientUI.ViewModel.ObservableContact.registerClass('ClientUI.ViewModel.ObservableContact',SparkleXrm.ViewModelBase);ClientUI.View.HelloWorldView.registerClass('ClientUI.View.HelloWorldView');ClientUI.View.HelloWorldView.vm=null;})();// This script was generated using Script# v0.7.4.0
